### PR TITLE
HAWKULAR-1275 Remove technical debt on LiveMetric

### PR DESCRIPTION
**Pull request by lucasponce**
The general context for this PR is related to https://issues.jboss.org/browse/HAWKULAR-1275.
Middleware Provider is going to be updated to use a new version of the Hawkular Services backend.

This provider uses LiveMetrics model to integrate with ManageIQ reports engine.

During the update in the provider we realized that there was some technical debt left in the core repo, so, that logic is moved into the provider, so any future change will be handled directly in the provider instead of core manage repo.

Also, this PR updates the LiveMetrics configuration as today a single entity (i.e. messaging) can support different metrics depending of the version, so version/ should be defined in configuration files.

Last, in performance reports, there were some technical debt brought from hMetrics implementation, like the *_max/_min/_avg suffixes for metrics. Those are removed and managed from backend as normal metrics instead as an exception that is not mapped with a real metric.

### CODE REVIEW

**Comment by lucasponce** [comment]
I am repeating the same PR I sent (and close) into ManageIQ core repo.

**Comment by lucasponce** [comment]
Please, don't start to review/merge, I see some things pending to add.

**Comment by lucasponce** [comment]
Ok, I have added the changes on the Datasource reports.

**Comment by jshaughn** [comment]
@israel-hdez , This looks good to me, please merge so I can test it locally.

**Pull request merged**
